[package]
name = "near-chain"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.4", features = ["serde"] }
log = "0.4"
failure = "0.1"
failure_derive = "0.1"
kvdb = "0.1"
protobuf = "2.4"
serde = "1.0"
serde_derive = "1.0"

primitives = { path = "../../runtime/primitives" }
near-protos = { path = "../../runtime/protos" }
near-store = { path = "../store" }
