cargo-features = ["profile-overrides"]

[package]
name = "nearcore"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[workspace]
members = [
    "protos/builder",
    "core/primitives",
    "core/store",
    "runtime/runtime",
    "runtime/wasm",
    "runtime/wasm/runtest",
    "ghost/chain",
    "ghost/pool",
    "ghost/client",
    "ghost/network",
    "ghost/jsonrpc",
    "ghost/near",
    "test-utils/keystore",
    "test-utils/testlib",
    "test-utils/loadtester",
]
exclude = [
    "runtime/wasm/runtest/generate-wasm/to-wasm",
]

[dev-dependencies]
lazy_static = "1.2.0"
log = "0.4.6"
rand = "0.6"
serde_json = "1.0.0"
reqwest = "0.9"

near-protos = { path = "./core/protos" }
primitives = { path = "./core/primitives" }
storage = { path = "./core/storage" }

keystore = { path = "./test-utils/keystore" }
testlib = { path = "./test-utils/testlib" }
node-runtime = { path = "./runtime/runtime" }
near = { path = "./ghost/near"}

[profile.release]
lto = true        # Enable full link-time optimization.
codegen-units = 1 # Use only 1 codegen-unit to enable full optimizations.

[profile.dev.overrides.pairing]
opt-level = 3 # pairing library is too slow to use in debug

[features]
expensive_tests = []
regression_tests = []
old_tests = []
