[package]
name = "near_pool"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
log = "0.4"
chrono = "0.4.4"
failure = "0.1"
failure_derive = "0.1"

primitives = { path = "../../runtime/primitives" }
near_chain = { path = "../chain" }
