[package]
name = "near-validator"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
bytes = "0.4"
actix = "0.8.1"
log = "0.4"
tokio = "0.1"
protobuf = "2.4"
futures = "0.1"
chrono = { version = "0.4.4", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
rand = "0.6.5"

primitives = { path = "../../runtime/primitives" }
near-chain = { path = "../chain" }