[package]
name = "testlib"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "generate-test-spec"
path = "src/generate_test_spec.rs"

[dependencies]
clap = "2.32"
log = "0.4"
rand = "0.6"
rand_xorshift = "0.1"
serde_json = "1.0.0"
tokio = "0.1"
futures = "0.1.25"
lazy_static = "1.3"
bs58 = "0.2"
byteorder = "1.2"
tempdir = "0.3"

near-primitives = { path = "../../core/primitives" }
near-protos = { path = "../../core/protos" }
near-store = { path = "../../core/store" }
node-runtime = { path = "../../runtime/runtime" }
near = { path = "../../chain/near" }

[dependencies.reqwest]
version = "0.9"
features = ["rustls-tls", "trust-dns"]

