[package]
name = "near-client"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
actix = "0.8.1"
kvdb = "0.1"
log = "0.4"

primitives = { path = "../../runtime/primitives" }
near-store = { path = "../store" }
near-chain = { path = "../chain" }
near-network = { path = "../network" }
near-pool = { path = "../pool" }
