[package]
name = "near"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
actix = "0.8.1"
base64 = "0.10.0"
kvdb = "0.1"
kvdb-memorydb = "0.1"
log = "0.4"
env_logger = "0.6.0"
chrono = { version = "0.4.4", features = ["serde"] }
futures = "0.1"
clap = "2.32"
rand = "0.6.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
dirs = "1.0.5"

near-primitives = { path = "../core/primitives" }
near-store = { path = "../core/store" }
node-runtime = { path = "../runtime/runtime" }

[dev-dependencies]
tempdir = "0.3"
