[package]
name = "near-store"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
kvdb = "0.1"
kvdb-memorydb = "0.1"
serde = "1.0"
serde_derive = "1.0"

primitives = { path = "../../runtime/primitives" }
