[package]
name = "near-store"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
kvdb = "0.1"
kvdb-memorydb = "0.1"
kvdb-rocksdb = "0.1.3"
serde = "1.0"
serde_derive = "1.0"
cached = "0.8"

primitives = { path = "../primitives" }
