[package]
name = "near-store"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
byteorder = "1.2"
kvdb = "0.1"
kvdb-memorydb = "0.1"
kvdb-rocksdb = "0.1.3"
serde = "1.0"
serde_derive = "1.0"
cached = { git = "https://github.com/nearprotocol/cached", rev = "7e472eddef68607e344d5a106a0e6705d92e55be" }

near-primitives = { path = "../primitives" }
