[package]
name = "near"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
actix = "0.8.1"
kvdb = "0.1"
kvdb-memorydb = "0.1"
log = "0.4"
env_logger = "0.6.0"

primitives = { path = "../../runtime/primitives" }
near_chain = { path = "../chain" }
near_client = { path = "../client" }
near_pool = { path = "../pool" }
near_network = { path = "../network" }