[package]
name = "near"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
actix = "0.8.1"
kvdb = "0.1"
kvdb-memorydb = "0.1"
log = "0.4"
env_logger = "0.6.0"
chrono = { version = "0.4.4", features = ["serde"] }
futures = "0.1"
clap = "2.32"

primitives = { path = "../../runtime/primitives" }
node-runtime = { path = "../../runtime/runtime" }
near-store = { path = "../store" }
near-chain = { path = "../chain" }
near-client = { path = "../client" }
near-pool = { path = "../pool" }
near-network = { path = "../network" }
near-jsonrpc = { path = "../jsonrpc" }